title: Residência BRISA
description: > # this means to ignore newlines until "baseurl:"
  Residência em TIC da BRISA/UnB FGA - Projetos 2023.1
permalink: ':title/'
baseurl: "/projetos_imersao" # the subpath of your site, e.g. /blog
url: "https://residenciaticbrisa.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: 
author-img: lappis.png
about-author: Residência BRISA - Projetos
social-email: caguiar@unb.br
social-github: rochacarla

# Build Settings
markdown: kramdown
plugins_dir:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 10
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
